name: Update iPhone Prices Data

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 lxml

      - name: Run scraper
        run: python simple_scraper.py

          - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add iphone_prices.csv
        git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update iPhone prices data"
        git push
        
    - name: Trigger Vercel redeploy
      run: |
        curl -X POST ${{ secrets.VERCEL_REDEPLOY_URL }} || echo "Vercel redeploy URL not configured"
